// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/birdple/falco/internal/processor"
	mock "github.com/stretchr/testify/mock"
)

// NewMockImageProcessor creates a new instance of MockImageProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageProcessor {
	mock := &MockImageProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageProcessor is an autogenerated mock type for the ImageProcessor type
type MockImageProcessor struct {
	mock.Mock
}

type MockImageProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageProcessor) EXPECT() *MockImageProcessor_Expecter {
	return &MockImageProcessor_Expecter{mock: &_m.Mock}
}

// GetCacheStats provides a mock function for the type MockImageProcessor
func (_mock *MockImageProcessor) GetCacheStats() interface{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCacheStats")
	}

	var r0 interface{}
	if returnFunc, ok := ret.Get(0).(func() interface{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	return r0
}

// MockImageProcessor_GetCacheStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCacheStats'
type MockImageProcessor_GetCacheStats_Call struct {
	*mock.Call
}

// GetCacheStats is a helper method to define mock.On call
func (_e *MockImageProcessor_Expecter) GetCacheStats() *MockImageProcessor_GetCacheStats_Call {
	return &MockImageProcessor_GetCacheStats_Call{Call: _e.mock.On("GetCacheStats")}
}

func (_c *MockImageProcessor_GetCacheStats_Call) Run(run func()) *MockImageProcessor_GetCacheStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImageProcessor_GetCacheStats_Call) Return(ifaceVal interface{}) *MockImageProcessor_GetCacheStats_Call {
	_c.Call.Return(ifaceVal)
	return _c
}

func (_c *MockImageProcessor_GetCacheStats_Call) RunAndReturn(run func() interface{}) *MockImageProcessor_GetCacheStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetContentType provides a mock function for the type MockImageProcessor
func (_mock *MockImageProcessor) GetContentType(format string) string {
	ret := _mock.Called(format)

	if len(ret) == 0 {
		panic("no return value specified for GetContentType")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(format)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockImageProcessor_GetContentType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContentType'
type MockImageProcessor_GetContentType_Call struct {
	*mock.Call
}

// GetContentType is a helper method to define mock.On call
//   - format string
func (_e *MockImageProcessor_Expecter) GetContentType(format interface{}) *MockImageProcessor_GetContentType_Call {
	return &MockImageProcessor_GetContentType_Call{Call: _e.mock.On("GetContentType", format)}
}

func (_c *MockImageProcessor_GetContentType_Call) Run(run func(format string)) *MockImageProcessor_GetContentType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageProcessor_GetContentType_Call) Return(s string) *MockImageProcessor_GetContentType_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockImageProcessor_GetContentType_Call) RunAndReturn(run func(format string) string) *MockImageProcessor_GetContentType_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetadata provides a mock function for the type MockImageProcessor
func (_mock *MockImageProcessor) GetMetadata(ctx context.Context, input io.Reader) (*processor.ImageMetadata, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetMetadata")
	}

	var r0 *processor.ImageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader) (*processor.ImageMetadata, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader) *processor.ImageMetadata); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*processor.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageProcessor_GetMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetadata'
type MockImageProcessor_GetMetadata_Call struct {
	*mock.Call
}

// GetMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - input io.Reader
func (_e *MockImageProcessor_Expecter) GetMetadata(ctx interface{}, input interface{}) *MockImageProcessor_GetMetadata_Call {
	return &MockImageProcessor_GetMetadata_Call{Call: _e.mock.On("GetMetadata", ctx, input)}
}

func (_c *MockImageProcessor_GetMetadata_Call) Run(run func(ctx context.Context, input io.Reader)) *MockImageProcessor_GetMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageProcessor_GetMetadata_Call) Return(imageMetadata *processor.ImageMetadata, err error) *MockImageProcessor_GetMetadata_Call {
	_c.Call.Return(imageMetadata, err)
	return _c
}

func (_c *MockImageProcessor_GetMetadata_Call) RunAndReturn(run func(ctx context.Context, input io.Reader) (*processor.ImageMetadata, error)) *MockImageProcessor_GetMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateCacheKey provides a mock function for the type MockImageProcessor
func (_mock *MockImageProcessor) GenerateCacheKey(storageKey string, params *processor.ProcessingParams) string {
	ret := _mock.Called(storageKey, params)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCacheKey")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, *processor.ProcessingParams) string); ok {
		r0 = returnFunc(storageKey, params)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockImageProcessor_GenerateCacheKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCacheKey'
type MockImageProcessor_GenerateCacheKey_Call struct {
	*mock.Call
}

func (_e *MockImageProcessor_Expecter) GenerateCacheKey(storageKey interface{}, params interface{}) *MockImageProcessor_GenerateCacheKey_Call {
	return &MockImageProcessor_GenerateCacheKey_Call{Call: _e.mock.On("GenerateCacheKey", storageKey, params)}
}

func (_c *MockImageProcessor_GenerateCacheKey_Call) Run(run func(storageKey string, params *processor.ProcessingParams)) *MockImageProcessor_GenerateCacheKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*processor.ProcessingParams))
	})
	return _c
}

func (_c *MockImageProcessor_GenerateCacheKey_Call) Return(s string) *MockImageProcessor_GenerateCacheKey_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockImageProcessor_GenerateCacheKey_Call) RunAndReturn(run func(string, *processor.ProcessingParams) string) *MockImageProcessor_GenerateCacheKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetFromCache provides a mock function for the type MockImageProcessor
func (_mock *MockImageProcessor) GetFromCache(key string) ([]byte, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetFromCache")
	}

	var r0 []byte
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockImageProcessor_GetFromCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFromCache'
type MockImageProcessor_GetFromCache_Call struct {
	*mock.Call
}

func (_e *MockImageProcessor_Expecter) GetFromCache(key interface{}) *MockImageProcessor_GetFromCache_Call {
	return &MockImageProcessor_GetFromCache_Call{Call: _e.mock.On("GetFromCache", key)}
}

func (_c *MockImageProcessor_GetFromCache_Call) Run(run func(key string)) *MockImageProcessor_GetFromCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockImageProcessor_GetFromCache_Call) Return(data []byte, found bool) *MockImageProcessor_GetFromCache_Call {
	_c.Call.Return(data, found)
	return _c
}

func (_c *MockImageProcessor_GetFromCache_Call) RunAndReturn(run func(string) ([]byte, bool)) *MockImageProcessor_GetFromCache_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateCacheForKey provides a mock function for the type MockImageProcessor
func (_mock *MockImageProcessor) InvalidateCacheForKey(storageKey string) int {
	ret := _mock.Called(storageKey)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateCacheForKey")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(storageKey)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockImageProcessor_InvalidateCacheForKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateCacheForKey'
type MockImageProcessor_InvalidateCacheForKey_Call struct {
	*mock.Call
}

func (_e *MockImageProcessor_Expecter) InvalidateCacheForKey(storageKey interface{}) *MockImageProcessor_InvalidateCacheForKey_Call {
	return &MockImageProcessor_InvalidateCacheForKey_Call{Call: _e.mock.On("InvalidateCacheForKey", storageKey)}
}

func (_c *MockImageProcessor_InvalidateCacheForKey_Call) Run(run func(storageKey string)) *MockImageProcessor_InvalidateCacheForKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockImageProcessor_InvalidateCacheForKey_Call) Return(n int) *MockImageProcessor_InvalidateCacheForKey_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockImageProcessor_InvalidateCacheForKey_Call) RunAndReturn(run func(string) int) *MockImageProcessor_InvalidateCacheForKey_Call {
	_c.Call.Return(run)
	return _c
}

// Process provides a mock function for the type MockImageProcessor
func (_mock *MockImageProcessor) Process(ctx context.Context, input io.Reader, params *processor.ProcessingParams, cacheKey string) (*processor.ProcessedImage, error) {
	ret := _mock.Called(ctx, input, params, cacheKey)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 *processor.ProcessedImage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, *processor.ProcessingParams, string) (*processor.ProcessedImage, error)); ok {
		return returnFunc(ctx, input, params, cacheKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, *processor.ProcessingParams, string) *processor.ProcessedImage); ok {
		r0 = returnFunc(ctx, input, params, cacheKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*processor.ProcessedImage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader, *processor.ProcessingParams, string) error); ok {
		r1 = returnFunc(ctx, input, params, cacheKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageProcessor_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockImageProcessor_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - input io.Reader
//   - params *processor.ProcessingParams
//   - cacheKey string
func (_e *MockImageProcessor_Expecter) Process(ctx interface{}, input interface{}, params interface{}, cacheKey interface{}) *MockImageProcessor_Process_Call {
	return &MockImageProcessor_Process_Call{Call: _e.mock.On("Process", ctx, input, params, cacheKey)}
}

func (_c *MockImageProcessor_Process_Call) Run(run func(ctx context.Context, input io.Reader, params *processor.ProcessingParams, cacheKey string)) *MockImageProcessor_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		var arg2 *processor.ProcessingParams
		if args[2] != nil {
			arg2 = args[2].(*processor.ProcessingParams)
		}
		arg3 := args[3].(string)
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockImageProcessor_Process_Call) Return(processedImage *processor.ProcessedImage, err error) *MockImageProcessor_Process_Call {
	_c.Call.Return(processedImage, err)
	return _c
}

func (_c *MockImageProcessor_Process_Call) RunAndReturn(run func(ctx context.Context, input io.Reader, params *processor.ProcessingParams, cacheKey string) (*processor.ProcessedImage, error)) *MockImageProcessor_Process_Call {
	_c.Call.Return(run)
	return _c
}

// SetCache provides a mock function for the type MockImageProcessor
func (_mock *MockImageProcessor) SetCache(cache processor.Cache) {
	_mock.Called(cache)
	return
}

// MockImageProcessor_SetCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCache'
type MockImageProcessor_SetCache_Call struct {
	*mock.Call
}

// SetCache is a helper method to define mock.On call
//   - cache processor.Cache
func (_e *MockImageProcessor_Expecter) SetCache(cache interface{}) *MockImageProcessor_SetCache_Call {
	return &MockImageProcessor_SetCache_Call{Call: _e.mock.On("SetCache", cache)}
}

func (_c *MockImageProcessor_SetCache_Call) Run(run func(cache processor.Cache)) *MockImageProcessor_SetCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 processor.Cache
		if args[0] != nil {
			arg0 = args[0].(processor.Cache)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageProcessor_SetCache_Call) Return() *MockImageProcessor_SetCache_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockImageProcessor_SetCache_Call) RunAndReturn(run func(cache processor.Cache)) *MockImageProcessor_SetCache_Call {
	_c.Run(run)
	return _c
}

// SupportedFormats provides a mock function for the type MockImageProcessor
func (_mock *MockImageProcessor) SupportedFormats() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportedFormats")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockImageProcessor_SupportedFormats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportedFormats'
type MockImageProcessor_SupportedFormats_Call struct {
	*mock.Call
}

// SupportedFormats is a helper method to define mock.On call
func (_e *MockImageProcessor_Expecter) SupportedFormats() *MockImageProcessor_SupportedFormats_Call {
	return &MockImageProcessor_SupportedFormats_Call{Call: _e.mock.On("SupportedFormats")}
}

func (_c *MockImageProcessor_SupportedFormats_Call) Run(run func()) *MockImageProcessor_SupportedFormats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImageProcessor_SupportedFormats_Call) Return(strings []string) *MockImageProcessor_SupportedFormats_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockImageProcessor_SupportedFormats_Call) RunAndReturn(run func() []string) *MockImageProcessor_SupportedFormats_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateFormat provides a mock function for the type MockImageProcessor
func (_mock *MockImageProcessor) ValidateFormat(format string) bool {
	ret := _mock.Called(format)

	if len(ret) == 0 {
		panic("no return value specified for ValidateFormat")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(format)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockImageProcessor_ValidateFormat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateFormat'
type MockImageProcessor_ValidateFormat_Call struct {
	*mock.Call
}

// ValidateFormat is a helper method to define mock.On call
//   - format string
func (_e *MockImageProcessor_Expecter) ValidateFormat(format interface{}) *MockImageProcessor_ValidateFormat_Call {
	return &MockImageProcessor_ValidateFormat_Call{Call: _e.mock.On("ValidateFormat", format)}
}

func (_c *MockImageProcessor_ValidateFormat_Call) Run(run func(format string)) *MockImageProcessor_ValidateFormat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageProcessor_ValidateFormat_Call) Return(b bool) *MockImageProcessor_ValidateFormat_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockImageProcessor_ValidateFormat_Call) RunAndReturn(run func(format string) bool) *MockImageProcessor_ValidateFormat_Call {
	_c.Call.Return(run)
	return _c
}
