// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type MockCache
func (_mock *MockCache) Clear() {
	_mock.Called()
	return
}

// MockCache_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockCache_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *MockCache_Expecter) Clear() *MockCache_Clear_Call {
	return &MockCache_Clear_Call{Call: _e.mock.On("Clear")}
}

func (_c *MockCache_Clear_Call) Run(run func()) *MockCache_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCache_Clear_Call) Return() *MockCache_Clear_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCache_Clear_Call) RunAndReturn(run func()) *MockCache_Clear_Call {
	_c.Run(run)
	return _c
}

// Contains provides a mock function for the type MockCache
func (_mock *MockCache) Contains(key string) bool {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Contains")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockCache_Contains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Contains'
type MockCache_Contains_Call struct {
	*mock.Call
}

// Contains is a helper method to define mock.On call
//   - key string
func (_e *MockCache_Expecter) Contains(key interface{}) *MockCache_Contains_Call {
	return &MockCache_Contains_Call{Call: _e.mock.On("Contains", key)}
}

func (_c *MockCache_Contains_Call) Run(run func(key string)) *MockCache_Contains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCache_Contains_Call) Return(b bool) *MockCache_Contains_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockCache_Contains_Call) RunAndReturn(run func(key string) bool) *MockCache_Contains_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCache
func (_mock *MockCache) Delete(key string) {
	_mock.Called(key)
	return
}

// MockCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCache_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key string
func (_e *MockCache_Expecter) Delete(key interface{}) *MockCache_Delete_Call {
	return &MockCache_Delete_Call{Call: _e.mock.On("Delete", key)}
}

func (_c *MockCache_Delete_Call) Run(run func(key string)) *MockCache_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCache_Delete_Call) Return() *MockCache_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCache_Delete_Call) RunAndReturn(run func(key string)) *MockCache_Delete_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockCache
func (_mock *MockCache) Get(key string) ([]byte, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockCache_Expecter) Get(key interface{}) *MockCache_Get_Call {
	return &MockCache_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockCache_Get_Call) Run(run func(key string)) *MockCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCache_Get_Call) Return(bytes []byte, b bool) *MockCache_Get_Call {
	_c.Call.Return(bytes, b)
	return _c
}

func (_c *MockCache_Get_Call) RunAndReturn(run func(key string) ([]byte, bool)) *MockCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Keys provides a mock function for the type MockCache
func (_mock *MockCache) Keys() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Keys")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockCache_Keys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Keys'
type MockCache_Keys_Call struct {
	*mock.Call
}

// Keys is a helper method to define mock.On call
func (_e *MockCache_Expecter) Keys() *MockCache_Keys_Call {
	return &MockCache_Keys_Call{Call: _e.mock.On("Keys")}
}

func (_c *MockCache_Keys_Call) Run(run func()) *MockCache_Keys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCache_Keys_Call) Return(strings []string) *MockCache_Keys_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockCache_Keys_Call) RunAndReturn(run func() []string) *MockCache_Keys_Call {
	_c.Call.Return(run)
	return _c
}

// Len provides a mock function for the type MockCache
func (_mock *MockCache) Len() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Len")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockCache_Len_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Len'
type MockCache_Len_Call struct {
	*mock.Call
}

// Len is a helper method to define mock.On call
func (_e *MockCache_Expecter) Len() *MockCache_Len_Call {
	return &MockCache_Len_Call{Call: _e.mock.On("Len")}
}

func (_c *MockCache_Len_Call) Run(run func()) *MockCache_Len_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCache_Len_Call) Return(n int) *MockCache_Len_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockCache_Len_Call) RunAndReturn(run func() int) *MockCache_Len_Call {
	_c.Call.Return(run)
	return _c
}

// MaxSize provides a mock function for the type MockCache
func (_mock *MockCache) MaxSize() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MaxSize")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockCache_MaxSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxSize'
type MockCache_MaxSize_Call struct {
	*mock.Call
}

// MaxSize is a helper method to define mock.On call
func (_e *MockCache_Expecter) MaxSize() *MockCache_MaxSize_Call {
	return &MockCache_MaxSize_Call{Call: _e.mock.On("MaxSize")}
}

func (_c *MockCache_MaxSize_Call) Run(run func()) *MockCache_MaxSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCache_MaxSize_Call) Return(n int64) *MockCache_MaxSize_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockCache_MaxSize_Call) RunAndReturn(run func() int64) *MockCache_MaxSize_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockCache
func (_mock *MockCache) Set(key string, value []byte, ttl time.Duration) error {
	ret := _mock.Called(key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, time.Duration) error); ok {
		r0 = returnFunc(key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value []byte
//   - ttl time.Duration
func (_e *MockCache_Expecter) Set(key interface{}, value interface{}, ttl interface{}) *MockCache_Set_Call {
	return &MockCache_Set_Call{Call: _e.mock.On("Set", key, value, ttl)}
}

func (_c *MockCache_Set_Call) Run(run func(key string, value []byte, ttl time.Duration)) *MockCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCache_Set_Call) Return(err error) *MockCache_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_Set_Call) RunAndReturn(run func(key string, value []byte, ttl time.Duration) error) *MockCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type MockCache
func (_mock *MockCache) Size() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockCache_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockCache_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockCache_Expecter) Size() *MockCache_Size_Call {
	return &MockCache_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockCache_Size_Call) Run(run func()) *MockCache_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCache_Size_Call) Return(n int64) *MockCache_Size_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockCache_Size_Call) RunAndReturn(run func() int64) *MockCache_Size_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function for the type MockCache
func (_mock *MockCache) Stats() interface{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 interface{}
	if returnFunc, ok := ret.Get(0).(func() interface{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	return r0
}

// MockCache_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockCache_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockCache_Expecter) Stats() *MockCache_Stats_Call {
	return &MockCache_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockCache_Stats_Call) Run(run func()) *MockCache_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCache_Stats_Call) Return(ifaceVal interface{}) *MockCache_Stats_Call {
	_c.Call.Return(ifaceVal)
	return _c
}

func (_c *MockCache_Stats_Call) RunAndReturn(run func() interface{}) *MockCache_Stats_Call {
	_c.Call.Return(run)
	return _c
}
