// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/birdple/imagine/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorageBackend creates a new instance of MockStorageBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageBackend {
	mock := &MockStorageBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorageBackend is an autogenerated mock type for the StorageBackend type
type MockStorageBackend struct {
	mock.Mock
}

type MockStorageBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageBackend) EXPECT() *MockStorageBackend_Expecter {
	return &MockStorageBackend_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockStorageBackend
func (_mock *MockStorageBackend) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageBackend_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorageBackend_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorageBackend_Expecter) Delete(ctx interface{}, key interface{}) *MockStorageBackend_Delete_Call {
	return &MockStorageBackend_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockStorageBackend_Delete_Call) Run(run func(ctx context.Context, key string)) *MockStorageBackend_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageBackend_Delete_Call) Return(err error) *MockStorageBackend_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageBackend_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockStorageBackend_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockStorageBackend
func (_mock *MockStorageBackend) Exists(ctx context.Context, key string) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageBackend_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockStorageBackend_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorageBackend_Expecter) Exists(ctx interface{}, key interface{}) *MockStorageBackend_Exists_Call {
	return &MockStorageBackend_Exists_Call{Call: _e.mock.On("Exists", ctx, key)}
}

func (_c *MockStorageBackend_Exists_Call) Run(run func(ctx context.Context, key string)) *MockStorageBackend_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageBackend_Exists_Call) Return(b bool, err error) *MockStorageBackend_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockStorageBackend_Exists_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, error)) *MockStorageBackend_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function for the type MockStorageBackend
func (_mock *MockStorageBackend) GetStats(ctx context.Context) (*storage.StorageStats, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *storage.StorageStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*storage.StorageStats, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *storage.StorageStats); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.StorageStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageBackend_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockStorageBackend_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorageBackend_Expecter) GetStats(ctx interface{}) *MockStorageBackend_GetStats_Call {
	return &MockStorageBackend_GetStats_Call{Call: _e.mock.On("GetStats", ctx)}
}

func (_c *MockStorageBackend_GetStats_Call) Run(run func(ctx context.Context)) *MockStorageBackend_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorageBackend_GetStats_Call) Return(storageStats *storage.StorageStats, err error) *MockStorageBackend_GetStats_Call {
	_c.Call.Return(storageStats, err)
	return _c
}

func (_c *MockStorageBackend_GetStats_Call) RunAndReturn(run func(ctx context.Context) (*storage.StorageStats, error)) *MockStorageBackend_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// Health provides a mock function for the type MockStorageBackend
func (_mock *MockStorageBackend) Health(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageBackend_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockStorageBackend_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorageBackend_Expecter) Health(ctx interface{}) *MockStorageBackend_Health_Call {
	return &MockStorageBackend_Health_Call{Call: _e.mock.On("Health", ctx)}
}

func (_c *MockStorageBackend_Health_Call) Run(run func(ctx context.Context)) *MockStorageBackend_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorageBackend_Health_Call) Return(err error) *MockStorageBackend_Health_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageBackend_Health_Call) RunAndReturn(run func(ctx context.Context) error) *MockStorageBackend_Health_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockStorageBackend
func (_mock *MockStorageBackend) List(ctx context.Context, prefix string) ([]storage.ListResult, error) {
	ret := _mock.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []storage.ListResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]storage.ListResult, error)); ok {
		return returnFunc(ctx, prefix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []storage.ListResult); ok {
		r0 = returnFunc(ctx, prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.ListResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prefix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageBackend_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockStorageBackend_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
func (_e *MockStorageBackend_Expecter) List(ctx interface{}, prefix interface{}) *MockStorageBackend_List_Call {
	return &MockStorageBackend_List_Call{Call: _e.mock.On("List", ctx, prefix)}
}

func (_c *MockStorageBackend_List_Call) Run(run func(ctx context.Context, prefix string)) *MockStorageBackend_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageBackend_List_Call) Return(listResults []storage.ListResult, err error) *MockStorageBackend_List_Call {
	_c.Call.Return(listResults, err)
	return _c
}

func (_c *MockStorageBackend_List_Call) RunAndReturn(run func(ctx context.Context, prefix string) ([]storage.ListResult, error)) *MockStorageBackend_List_Call {
	_c.Call.Return(run)
	return _c
}

// Retrieve provides a mock function for the type MockStorageBackend
func (_mock *MockStorageBackend) Retrieve(ctx context.Context, key string) (io.ReadCloser, *storage.ImageMetadata, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Retrieve")
	}

	var r0 io.ReadCloser
	var r1 *storage.ImageMetadata
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, *storage.ImageMetadata, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *storage.ImageMetadata); ok {
		r1 = returnFunc(ctx, key)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*storage.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, key)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStorageBackend_Retrieve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retrieve'
type MockStorageBackend_Retrieve_Call struct {
	*mock.Call
}

// Retrieve is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorageBackend_Expecter) Retrieve(ctx interface{}, key interface{}) *MockStorageBackend_Retrieve_Call {
	return &MockStorageBackend_Retrieve_Call{Call: _e.mock.On("Retrieve", ctx, key)}
}

func (_c *MockStorageBackend_Retrieve_Call) Run(run func(ctx context.Context, key string)) *MockStorageBackend_Retrieve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageBackend_Retrieve_Call) Return(readCloser io.ReadCloser, imageMetadata *storage.ImageMetadata, err error) *MockStorageBackend_Retrieve_Call {
	_c.Call.Return(readCloser, imageMetadata, err)
	return _c
}

func (_c *MockStorageBackend_Retrieve_Call) RunAndReturn(run func(ctx context.Context, key string) (io.ReadCloser, *storage.ImageMetadata, error)) *MockStorageBackend_Retrieve_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type MockStorageBackend
func (_mock *MockStorageBackend) Store(ctx context.Context, key string, data io.Reader, metadata *storage.ImageMetadata) error {
	ret := _mock.Called(ctx, key, data, metadata)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, *storage.ImageMetadata) error); ok {
		r0 = returnFunc(ctx, key, data, metadata)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageBackend_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockStorageBackend_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - data io.Reader
//   - metadata *storage.ImageMetadata
func (_e *MockStorageBackend_Expecter) Store(ctx interface{}, key interface{}, data interface{}, metadata interface{}) *MockStorageBackend_Store_Call {
	return &MockStorageBackend_Store_Call{Call: _e.mock.On("Store", ctx, key, data, metadata)}
}

func (_c *MockStorageBackend_Store_Call) Run(run func(ctx context.Context, key string, data io.Reader, metadata *storage.ImageMetadata)) *MockStorageBackend_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 *storage.ImageMetadata
		if args[3] != nil {
			arg3 = args[3].(*storage.ImageMetadata)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorageBackend_Store_Call) Return(err error) *MockStorageBackend_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageBackend_Store_Call) RunAndReturn(run func(ctx context.Context, key string, data io.Reader, metadata *storage.ImageMetadata) error) *MockStorageBackend_Store_Call {
	_c.Call.Return(run)
	return _c
}
