packages:
  github.com/birdple/falco/internal/storage:
    config:
      filename: "mock_{{.InterfaceName}}.go"
      dir: "tests/mocks"
    interfaces:
      StorageBackend:
  github.com/birdple/falco/internal/processor:
    config:
      filename: "mock_{{.InterfaceName}}.go"
      dir: "tests/mocks"
    interfaces:
      Cache:
      ImageProcessor:
